<?php

namespace modules\statik\helpers;

use Craft;
use craft\base\ElementInterface;
use craft\base\Field;
use craft\base\FieldInterface;
use craft\elements\Entry;
use craft\fields\BaseOptionsField;
use craft\fields\Checkboxes;
use craft\fields\data\SingleOptionFieldData;
use craft\fields\Lightswitch;
use craft\fields\MultiSelect;
use craft\fields\PlainText;
use modules\statik\fields\AnchorLink;

/**
 * Decides which Content Builder block fields are "variable" for the showcase generated by
 * `craft statik/contentbuilder`, and describes the variation a block instance is in.
 * Shared by the console command and the `_contentBuilder` template so both stay in sync.
 *
 * Per field:
 *  - option fields (Position, Width, Config Values, Dropdown, Radio Buttons, Button Group) → one value per option
 *  - lightswitches → on / off
 *  - any other optional field → filled / empty
 *  - required fields → always filled (not a dimension)
 */
class ContentbuilderShowcase
{
    private const OPTION_FIELD_TYPES = [
        'rias\positionfieldtype\fields\Position',
        'rias\widthfieldtype\fields\Width',
    ];
    public const SECTION_HANDLE = 'pages';
    public const DEFAULT_SLUG = 'contentbuilder';
    public const CONTENT_PATH = CRAFT_BASE_PATH . '/config/contentbuilder-showcase/content.json';

    private const LONG_TITLE_LENGTH = 100;
    private const CONFIG_VALUES_FIELD_TYPE = 'statikbe\configvaluesfield\fields\ConfigValuesFieldField';

    /**
     * Slug of the showcase parent page, from config/custom.php → contentbuilderShowcaseSlug.
     */
    public static function parentSlug(): string
    {
        return Craft::$app->getConfig()->custom->contentbuilderShowcaseSlug ?? self::DEFAULT_SLUG;
    }

    public static function findParentPage(): ?Entry
    {
        return Entry::find()->section(self::SECTION_HANDLE)->slug(self::parentSlug())->level(1)->status(null)->one();
    }

    /**
     * The values a field can vary over. A single value means it is not a dimension.
     * `true` = filled with content, `false` = left empty; anything else is the literal field value.
     * Extend this when blocks get new kinds of variant fields.
     */
    public static function dimensionValues(FieldInterface $field): array
    {
        if ($field instanceof Lightswitch) {
            return [true, false];
        }

        // Position / Width fields: options is [value => '1' (enabled) | '']
        if (in_array($field::class, self::OPTION_FIELD_TYPES, true)) {
            return array_map('strval', array_keys(array_filter($field->options ?? [])));
        }

        if ($field::class === self::CONFIG_VALUES_FIELD_TYPE) {
            $data = \statikbe\configvaluesfield\ConfigValuesField::getInstance()->getSettings()->data[$field->dataSet] ?? [];
            return array_map('strval', array_keys($data));
        }

        // Single-choice option fields (Dropdown, Radio Buttons, Button Group); multi-select ones are treated as content
        if ($field instanceof BaseOptionsField && !$field instanceof Checkboxes && !$field instanceof MultiSelect) {
            $values = [];
            foreach ($field->options as $option) {
                if (!isset($option['optgroup']) && ($option['value'] ?? '') !== '') {
                    $values[] = (string)$option['value'];
                }
            }
            return $values;
        }

        return self::isRequired($field) ? [true] : [true, false];
    }

    public static function isDimension(FieldInterface $field): bool
    {
        return count(self::dimensionValues($field)) > 1;
    }

    /**
     * Title-like fields get an excessively long value in one instance per block: Title (Anchor) fields and
     * plain text fields with "title" in their handle.
     */
    public static function isTitleField(FieldInterface $field): bool
    {
        return $field instanceof AnchorLink || ($field instanceof PlainText && stripos($field->handle, 'title') !== false);
    }

    public static function isRequired(FieldInterface $field): bool
    {
        /** @var Field $field */
        return (bool)($field->layoutElement?->required ?? $field->required ?? false);
    }

    public static function fieldLabel(FieldInterface $field): string
    {
        /** @var Field $field */
        return $field->layoutElement?->label ?: $field->name;
    }

    public static function formatValue(FieldInterface $field, mixed $value): string
    {
        if (is_bool($value)) {
            return $field instanceof Lightswitch ? ($value ? 'on' : 'off') : ($value ? 'yes' : 'no');
        }
        return (string)$value;
    }

    /**
     * Describes the variation a block instance is in, e.g. "Title: yes · Image position: right · Background Color: section--light".
     */
    public static function describe(ElementInterface $block): string
    {
        $parts = [];
        foreach ($block->getFieldLayout()?->getCustomFields() ?? [] as $field) {
            if (!self::isDimension($field)) {
                continue;
            }
            $value = $block->getFieldValue($field->handle);
            if ($field instanceof Lightswitch) {
                $value = (bool)$value;
            } elseif (self::dimensionValues($field) === [true, false]) {
                // filled / empty dimension; "long" marks the long-title stress example
                $isLong = self::isTitleField($field) && is_string($value) && mb_strlen($value) > self::LONG_TITLE_LENGTH;
                $value = $isLong ? 'long' : !$field->isValueEmpty($value, $block);
            } elseif ($value instanceof SingleOptionFieldData) {
                $value = $value->value;
            }
            $parts[] = self::fieldLabel($field) . ': ' . self::formatValue($field, $value);
        }
        return implode(' · ', $parts);
    }
}
