<?php

namespace modules\statik\helpers;

use Craft;
use craft\base\ElementInterface;
use craft\base\Field;
use craft\base\FieldInterface;
use craft\elements\db\ElementQueryInterface;
use craft\elements\Entry;
use craft\fields\BaseOptionsField;
use craft\fields\Checkboxes;
use craft\fields\data\SingleOptionFieldData;
use craft\fields\Entries as EntriesField;
use craft\fields\Lightswitch;
use craft\fields\Matrix;
use craft\fields\MultiSelect;
use craft\fields\PlainText;
use modules\statik\fields\AnchorLink;

/**
 * Decides which Content Builder block fields are "variable" for the showcase generated by
 * `craft statik/contentbuilder`, and describes the variation a block instance is in.
 * Shared by the console command and the `_contentBuilder` template so both stay in sync.
 *
 * Per field:
 *  - option fields (Position, Width, Config Values, Dropdown, Radio Buttons, Button Group) → one value per option
 *  - lightswitches → on / off
 *  - Matrix fields with a min and max number of entries → one value per item count
 *  - Entries fields → one value per item count (3, 2, 1; plus 0 when optional)
 *  - any other optional field → filled / empty
 *  - required fields → always filled (not a dimension)
 */
class ContentbuilderShowcase
{
    private const OPTION_FIELD_TYPES = [
        'rias\positionfieldtype\fields\Position',
        'rias\widthfieldtype\fields\Width',
    ];
    public const SECTION_HANDLE = 'pages';
    public const DEFAULT_SLUG = 'contentbuilder';
    public const GRID_DEFAULT_SLUG = 'gridbuilder';
    public const CONTENT_PATH = CRAFT_BASE_PATH . '/config/contentbuilder-showcase/content.json';

    private const LONG_TITLE_LENGTH = 100;
    private const MAX_COUNT_VARIATIONS = 3;
    private const CONFIG_VALUES_FIELD_TYPE = 'statikbe\configvaluesfield\fields\ConfigValuesFieldField';

    /**
     * Slug of the showcase parent page, from config/custom.php → contentbuilderShowcaseSlug.
     */
    public static function parentSlug(): string
    {
        return Craft::$app->getConfig()->custom->contentbuilderShowcaseSlug ?? self::DEFAULT_SLUG;
    }

    public static function findParentPage(): ?Entry
    {
        return self::findRootPage(self::parentSlug());
    }

    /**
     * Slug of the content row showcase parent page (column types and their combinations), from config/custom.php → gridbuilderShowcaseSlug.
     */
    public static function gridParentSlug(): string
    {
        return Craft::$app->getConfig()->custom->gridbuilderShowcaseSlug ?? self::GRID_DEFAULT_SLUG;
    }

    public static function findGridParentPage(): ?Entry
    {
        return self::findRootPage(self::gridParentSlug());
    }

    private static function findRootPage(string $slug): ?Entry
    {
        return Entry::find()->section(self::SECTION_HANDLE)->slug($slug)->level(1)->status(null)->one();
    }

    /**
     * Whether this page is part of one of the showcases (below the content builder or content row showcase parent page).
     */
    public static function isShowcasePage(?ElementInterface $page): bool
    {
        if (!$page instanceof Entry || $page->level < 2 || $page->getSection()?->handle !== self::SECTION_HANDLE) {
            return false;
        }
        $root = $page->getAncestors()->level(1)->status(null)->one();
        return in_array($root?->slug, [self::parentSlug(), self::gridParentSlug()], true);
    }

    /** Slug of the content row showcase page that renders the content builder at 2/3 width, like a page with a sidebar */
    public const GRID_NARROW_SLUG = 'two-thirds-page';

    /**
     * Whether this is the 2/3-width grid showcase page: content rows there follow the rules for 2/3 pages (GridBuilder::isNarrow())
     * and _contentBuilder.twig renders the builder at 2/3 width.
     */
    public static function isNarrowPage(?ElementInterface $page): bool
    {
        return $page instanceof Entry
            && $page->slug === self::GRID_NARROW_SLUG
            && $page->level == 2
            && $page->getParent()?->slug === self::gridParentSlug();
    }

    /**
     * The values a field can vary over. A single value means it is not a dimension.
     * `true` = filled with content, `false` = left empty; anything else is the literal field value.
     * Extend this when blocks get new kinds of variant fields.
     */
    public static function dimensionValues(FieldInterface $field): array
    {
        if ($field instanceof Lightswitch) {
            return [true, false];
        }

        // Position / Width fields: options is [value => '1' (enabled) | '']
        if (in_array($field::class, self::OPTION_FIELD_TYPES, true)) {
            return array_map('strval', array_keys(array_filter($field->options ?? [])));
        }

        if ($field::class === self::CONFIG_VALUES_FIELD_TYPE) {
            $data = \statikbe\configvaluesfield\ConfigValuesField::getInstance()->getSettings()->data[$field->dataSet] ?? [];
            return array_map('strval', array_keys($data));
        }

        // Single-choice option fields (Dropdown, Radio Buttons, Button Group); multi-select ones are treated as content
        if ($field instanceof BaseOptionsField && !$field instanceof Checkboxes && !$field instanceof MultiSelect) {
            $values = [];
            foreach ($field->options as $option) {
                if (!isset($option['optgroup']) && ($option['value'] ?? '') !== '') {
                    $values[] = (string)$option['value'];
                }
            }
            return $values;
        }

        // Matrix fields with a min and max number of entries → one value per item count (e.g. 2 or 3 columns)
        if (self::isCountMatrix($field)) {
            return range((int)$field->minEntries, (int)$field->maxEntries);
        }

        // Entries fields → one value per item count, largest first so the other variations show a full row
        if ($field instanceof EntriesField) {
            $max = min((int)($field->maxRelations ?: self::MAX_COUNT_VARIATIONS), self::MAX_COUNT_VARIATIONS);
            $min = max((int)$field->minRelations, self::isRequired($field) ? 1 : 0);
            return $max > $min ? range($max, $min) : [true];
        }

        return self::isRequired($field) ? [true] : [true, false];
    }

    public static function isCountField(FieldInterface $field): bool
    {
        return self::isCountMatrix($field) || ($field instanceof EntriesField && self::isDimension($field));
    }

    public static function isCountMatrix(FieldInterface $field): bool
    {
        return $field instanceof Matrix && $field->minEntries && $field->maxEntries
            && $field->maxEntries > $field->minEntries && $field->maxEntries - $field->minEntries <= self::MAX_COUNT_VARIATIONS;
    }

    public static function isDimension(FieldInterface $field): bool
    {
        return count(self::dimensionValues($field)) > 1;
    }

    /**
     * Title-like fields get an excessively long value in one instance per block: Title (Anchor) fields and
     * plain text fields with "title" in their handle.
     */
    public static function isTitleField(FieldInterface $field): bool
    {
        return $field instanceof AnchorLink || ($field instanceof PlainText && stripos($field->handle, 'title') !== false);
    }

    public static function isRequired(FieldInterface $field): bool
    {
        /** @var Field $field */
        return (bool)($field->layoutElement?->required ?? $field->required ?? false);
    }

    public static function fieldLabel(FieldInterface $field): string
    {
        /** @var Field $field */
        return $field->layoutElement?->label ?: $field->name;
    }

    public static function formatValue(FieldInterface $field, mixed $value): string
    {
        if (is_bool($value)) {
            return $field instanceof Lightswitch ? ($value ? 'on' : 'off') : ($value ? 'yes' : 'no');
        }
        return (string)$value;
    }

    /**
     * Describes the variation a block instance is in, e.g. "Title: yes · Image position: right · Background Color: section--light".
     */
    public static function describe(ElementInterface $block): string
    {
        if ($block instanceof Entry && $block->getType()->handle === GridBuilder::ROW_TYPE) {
            return self::describeGridRow($block);
        }

        $parts = [];
        foreach ($block->getFieldLayout()?->getCustomFields() ?? [] as $field) {
            if (!self::isDimension($field)) {
                continue;
            }
            $value = $block->getFieldValue($field->handle);
            if ($field instanceof Lightswitch) {
                $value = (bool)$value;
            } elseif (self::isCountField($field)) {
                $count = (int)($value instanceof ElementQueryInterface ? $value->count() : count($value));
                $value = $count . ($count === 1 ? ' item' : ' items');
            } elseif (self::dimensionValues($field) === [true, false]) {
                // filled / empty dimension; "long" marks the long-title stress example
                $isLong = self::isTitleField($field) && is_string($value) && mb_strlen($value) > self::LONG_TITLE_LENGTH;
                $value = $isLong ? 'long' : !$field->isValueEmpty($value, $block);
            } elseif ($value instanceof SingleOptionFieldData) {
                $value = $value->value;
            }
            $parts[] = self::fieldLabel($field) . ': ' . self::formatValue($field, $value);
        }
        return implode(' · ', $parts);
    }

    /**
     * E.g. "Layout: ⅓ + ⅔ · Columns: Image 1/3 | Text 2/3 [Title: no · Text: yes] · Vertical alignment: Top · Background Color: section--light".
     */
    private static function describeGridRow(Entry $row): string
    {
        $grid = GridBuilder::row($row);
        $columns = array_map(function(array $column) {
            $cell = $column['cell'];
            $variation = self::describe($cell);
            return Craft::t('site', $cell->getType()->name) . ' ' . GridBuilder::formatWidth($column['width']) . ($variation ? " [{$variation}]" : '');
        }, $grid['columns']);

        return implode(' · ', array_filter([
            'Layout: ' . ($row->getFieldValue(GridBuilder::LAYOUT_FIELD)?->label ?? $grid['layout']),
            'Columns: ' . implode(' | ', $columns),
            'Vertical alignment: ' . ($row->getFieldValue('gridAlignment')?->label ?? 'Top'),
            'Background Color: ' . (string)$row->getFieldValue('backgroundColor'),
            $grid['narrow'] ? 'Page: 2/3 wide' : null,
        ]));
    }
}
