color: blue
fieldLayouts:
  8e0153f8-35f6-4a49-bc77-316bc5dce081:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T12:37:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c32072f9-8c47-4064-8879-3ee67c000d42
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: titleColumn1
            includeInCards: false
            instructions: null
            label: 'Title Column 1'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a094285-054f-4607-8dcd-1fc94fb82b74
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:46:31+00:00'
            elementCondition: null
            fieldUid: 1ea43556-c1c6-4ae7-9c49-48498a82f797 # CK Editor - Extended
            handle: textColumn1
            includeInCards: false
            instructions: null
            label: 'Text Column 1'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0d886da-4888-441c-a187-8e98ed6323ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            elementCondition: null
            fieldUid: 71d59fcf-f766-4db1-a6fe-87bf1ce1b1ba # Call to action
            handle: ctaColumn1
            includeInCards: false
            instructions: null
            label: 'Call to action Column 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b059c4d7-8821-480d-8a5e-55ef53c9408a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: titleColumn2
            includeInCards: false
            instructions: null
            label: 'Title column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2064bb0-6d99-4e23-b2f4-dda597a2dfd1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:46:31+00:00'
            elementCondition: null
            fieldUid: 1ea43556-c1c6-4ae7-9c49-48498a82f797 # CK Editor - Extended
            handle: textColumn2
            includeInCards: false
            instructions: null
            label: 'Text Column 2'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fff5459c-5f10-4c23-bb07-5383ac951814
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            elementCondition: null
            fieldUid: 71d59fcf-f766-4db1-a6fe-87bf1ce1b1ba # Call to action
            handle: ctaColumn2
            includeInCards: false
            instructions: null
            label: 'Call to action Column 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 265f69af-07ca-49ed-99ff-7e54c504df5d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be3768d8-1b95-45d0-9a36-ccd08c889dd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a9d5fcb-7371-45df-b9f8-0a603830f3a3
        userCondition: null
handle: textTwoColumns
hasTitleField: false
icon: text
name: 'Text (2 columns)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
