allowLineBreaksInTitles: false
color: sky
description: null
fieldLayouts:
  75a5eaf0-5e4e-4a95-8c51-5778818897a7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "## For safe use, we only allow embeds with https links, else the embed will not be shown.\r\nFor more info about how to use this block, take a look at [our embed article](https://www.help.statik.be/embed)."
            dateAdded: '2026-10-07T16:04:30+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: d30a63e0-48d1-464e-acc2-9fd2c7165bc7
            userCondition: null
            width: 100
          -
            dateAdded: '2026-10-07T16:04:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 640b2fe5-663c-4a9a-9189-57771af174b0 # Embed
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9348e23-7c4f-472a-bd83-b65151c7e316
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:04:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f5036827-2f12-4c47-8a20-6118776dfb23 # Mobile order
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d32b063-0909-4df9-a9f3-a7a7aba90656
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce3f87ed-654a-4863-908d-1fec57a0d1ff
        userCondition: null
    thumbFieldKey: null
handle: cellEmbed
hasTitleField: false
icon: code
name: 'Cell – Embed'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{{ (object.embed ?? '') matches '/src=\"https?:\\\\/\\\\//' ? object.embed|replace('/^.*?src=\"https?:\\\\/\\\\/([^\\\\/\"]+).*$/s', '$1') : 'Embed' }}{{ object.mobileOrder.value ? ' · #' ~ object.mobileOrder.value ~ ' on mobile' }}"
