allowLineBreaksInTitles: false
color: green
description: null
fieldLayouts:
  86c388ab-0110-41c1-adbe-20fd2dc2af90:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:8db7534c-8bd4-420d-8cdd-eb8820561d03'
      - 'layoutElement:50f5dd66-ce34-4561-bd88-5d4a156fc95d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: null
            instructions: null
            label: Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1997073-bdf9-4c1f-a4ac-7640b5f1424d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ea43556-c1c6-4ae7-9c49-48498a82f797 # CK Editor - Extended
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8db7534c-8bd4-420d-8cdd-eb8820561d03
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f936530d-29a5-4460-9ccd-b586bfb25329 # Call to actions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50f5dd66-ce34-4561-bd88-5d4a156fc95d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b58b47cd-c00d-4ef4-8246-c8c52949c561 # Lightswitch (Default Off)
            handle: firstOnMobile
            instructions: 'Show this column above the other columns when they are stacked on small screens.'
            label: 'First on mobile'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa728870-e030-4785-ad9a-7b94dca2e143
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b77f0bf6-0dc6-43e8-8c4a-a50c3fd1a9b9
        userCondition: null
    thumbFieldKey: null
handle: cellText
hasTitleField: false
icon: paragraph
name: 'Cell – Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{{ object.blockTitle ?: (object.text ?? '')|striptags|trim|truncate(60) }}{{ object.firstOnMobile ? ' · first on mobile' }}"
