allowLineBreaksInTitles: false
color: amber
description: null
fieldLayouts:
  c6f31cc3-12b3-4d6f-9a54-d881d2d542bb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-07T16:03:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2710152c-60b2-4e0b-a982-4250def4c04b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:03:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9084b802-1468-4763-a867-2e4b1ebd3f09 # Show larger version in popup
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12a22c65-affc-4684-9fa5-ffd363c1bd6f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:03:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b58b47cd-c00d-4ef4-8246-c8c52949c561 # Lightswitch (Default Off)
            handle: firstOnMobile
            instructions: 'Show this column above the other columns when they are stacked on small screens.'
            label: 'First on mobile'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 012d55a9-b62b-4933-98ec-a9f5d29b5470
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a557581c-be98-4f2c-90c6-8de12091a4e3
        userCondition: null
    thumbFieldKey: 'layoutElement:2710152c-60b2-4e0b-a982-4250def4c04b'
handle: cellImage
hasTitleField: false
icon: image
name: 'Cell – Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{{ object.image.one().title ?? '' }}{{ object.firstOnMobile ? ' · first on mobile' }}"
