allowLineBreaksInTitles: false
color: green
description: null
fieldLayouts:
  6aa1dd63-bb58-46d8-b9d4-4faf2c49e37a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0ae7aca0-8626-4182-9eec-e9aed42c8f8f # Title + Text
            handle: faqBlock
            instructions: null
            label: 'FAQ items'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b31225f1-d3b7-4b62-a58b-e5843918b1bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98e31288-dd51-4007-909a-f0dab38d1346
        userCondition: null
    thumbFieldKey: null
handle: cellFaq
hasTitleField: false
icon: circle-question
name: 'Cell – FAQ'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
