allowLineBreaksInTitles: false
color: amber
description: null
fieldLayouts:
  6360b7eb-8848-4eae-9972-81cbbd08cf65:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:d728aef1-89eb-40a9-be90-a8937a2b4d59'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-07T16:03:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a # Video
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d728aef1-89eb-40a9-be90-a8937a2b4d59
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-10-07T16:03:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 724561c2-845a-427f-b005-e0c2a35e0112 # Placeholder Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa74636-4c76-47ee-ab66-b753b7ee9a37
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-10-07T16:03:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Caption
            handle: videoCaption
            instructions: null
            label: 'Video Caption'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 749d1882-8eb8-44b5-aa81-cac0e941d32a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:03:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f5036827-2f12-4c47-8a20-6118776dfb23 # Mobile order
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbe2de7c-6029-47e2-9960-aa0defe87374
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 70cdc1d5-d6b3-48f7-b54e-2e1b879640bb
        userCondition: null
    thumbFieldKey: 'layoutElement:3aa74636-4c76-47ee-ab66-b753b7ee9a37'
handle: cellVideo
hasTitleField: false
icon: video
name: 'Cell – Video'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{{ (object.videoCaption ?? '')|striptags|trim|truncate(60) ?: object.video }}{{ object.mobileOrder.value ? ' · #' ~ object.mobileOrder.value ~ ' on mobile' }}"
