allowLineBreaksInTitles: false
color: amber
description: null
fieldLayouts:
  d9b250af-e37e-44c4-8017-dd025a5cf672:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-07T16:04:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 74a30650-eb90-462f-a104-de1d41ac8221 # Form
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccffc467-d668-4220-b184-29141e580e58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:04:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f5036827-2f12-4c47-8a20-6118776dfb23 # Mobile order
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d0f327f-007b-4c6e-a224-a3d5beb149a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11b4b9fe-23de-4027-92ca-4a667da85477
        userCondition: null
    thumbFieldKey: null
handle: cellForm
hasTitleField: false
icon: envelope
name: 'Cell – Form'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{{ object.form.one().title ?? '' }}{{ object.mobileOrder.value ? ' · #' ~ object.mobileOrder.value ~ ' on mobile' }}"
