allowLineBreaksInTitles: false
color: sky
description: null
fieldLayouts:
  fbb43a86-b5e1-4bad-a790-096f399c33f7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-07T16:02:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0dda4c89-0265-41b5-bf85-6bbe323a3319 # Grid layout
            handle: null
            instructions: null
            label: Layout
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abd2c7f2-012a-40b0-9d0a-f4479f6acca9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:02:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 58a5b291-3206-4425-a43d-b73fc06fe746 # Grid cells
            handle: null
            instructions: null
            label: Columns
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfb16665-494f-44dd-ade1-3d95a71bfa18
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:02:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4eb325b-f36c-41bf-b1e5-fa4b8fde2edc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-10-07T16:02:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 15205848-f301-49cf-acd2-984e0a9963a4 # Grid vertical alignment
            handle: null
            instructions: null
            label: 'Vertical alignment'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5f1db04-6aa2-4641-abfb-92e6f06f57ab
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7f8d617b-8f1a-4217-b3b5-0e9b09fc516f
        userCondition: null
    thumbFieldKey: null
handle: gridRow
hasTitleField: false
icon: diagram-cells
name: 'Content row'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{{ object.gridLayout.label }}'
