color: blue
fieldLayouts:
  0b203f95-b680-4192-8ebc-fd84ef05fc3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d8e874f-1f56-4d56-b101-3f39004c5042
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4e415e-c7d5-4058-8bca-22cd1b5a7165
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 776fa716-10bb-48bb-ae08-28870f9d77e7 # Entries
            handle: null
            includeInCards: true
            instructions: null
            label: Entries
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76be8a95-7f6d-46e0-a7ad-0105ea2dc848
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a355fb7a-945c-4ac4-93bb-d5c240b57b9b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17a9de58-71d7-452f-a480-1439982cf48e
        userCondition: null
handle: overview
hasTitleField: false
icon: grid-2
name: Overview
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
