allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  beed5b6a-c667-4255-b97e-5805e5c1f3cf:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-13T13:17:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 81d7c1b0-05c8-44cc-95a5-ba284247c99e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8ff8437a-a38f-47f0-b489-1701614eec3f # Header image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fde1857-1709-40b4-8b39-d09a1cf1093d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63289059-5cef-4b1d-aa95-76bc5104d26b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5ab66e9a-a4bc-429d-9519-9638152f7efc
            userCondition: null
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24f3b8be-7ecd-4988-8342-93dedd6b8f52
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9911a5cc-bee9-4b4f-a601-2ff1795fcbc7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 66954acb-77ba-4c75-9659-f3976770df07 # CK Editor - Simple
            handle: sidebarText
            instructions: 'Shown below the sub-navigation.'
            label: 'Sidebar text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3deff569-2265-4ac4-aa01-2572a205dfbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f936530d-29a5-4460-9ccd-b586bfb25329 # Call to actions
            handle: sidebarCtas
            instructions: null
            label: 'Sidebar call to actions'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c5730c1-513f-4195-826a-fd881eee8c8f
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: 4ff3ba0d-79e0-4e84-b805-b7553148d3f2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-13T13:18:35+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Deze velden worden gebruikt om bv. kortere titel of introtekst, andere afbeelding te tonen als je deze entry elders op de website wil weergeven via een overview blok. Laat je deze velden leeg, dan wordt standaard de titel, intro of header/hero image getoond.'
            type: craft\fieldlayoutelements\Tip
            uid: 23b352e8-026d-4a31-9614-bd38d1758c1f
            userCondition: null
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82ad497c-8dfb-4daf-9051-69b59683cbba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8feb39d3-6d8b-45ef-8465-34b214074f87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f18217a-eec4-4a69-8bb0-96ccd6706d68
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: a656d1de-6911-4155-a942-5e6b3ee8f197
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-13T13:18:35+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: "Als je deze velden leeg laat, wordt standaard de Entry Title gebruikt als SEO Meta Title.\r\n\r\nLet op: de Meta tags die je hier invult, vormen louter een suggestie voor zoekmachines. De effectieve weergave in zoekresultaten kan afwijkend zijn."
            type: craft\fieldlayoutelements\Tip
            uid: f7028bf8-dc81-4f2d-ab77-16890fa5766e
            userCondition: null
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1c57676-3e38-4ee3-92eb-5ea370339fe8
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 1007693a-47d5-4380-8cb1-9da381b0eeae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-13T13:17:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 82edb6db-a497-4e37-8c25-5d4d210f0c81 # Search keywords
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e4cf80c-9ec5-460e-88a8-1a427a302404
            userCondition: null
            warning: null
            width: 100
        name: 'Site search'
        uid: 4b985820-5b5b-41ec-b5b3-6fc89a33c134
        userCondition: null
    thumbFieldKey: null
handle: pageWithSidebar
hasTitleField: true
icon: table-layout
name: 'Page with sidebar'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
