allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  8e0153f8-35f6-4a49-bc77-316bc5dce081:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-28T16:19:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0f4bced5-a875-4e8b-890c-16d25f45fce5 # Text column blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a2216da-e270-439f-93aa-7f100c83bd89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be3768d8-1b95-45d0-9a36-ccd08c889dd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a9d5fcb-7371-45df-b9f8-0a603830f3a3
        userCondition: null
    thumbFieldKey: null
handle: textColumns
hasTitleField: false
icon: text
name: 'Text columns'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
