allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ad0594dc-3a8b-40c8-b069-63f995b77418:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-28T16:18:20+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5779f377-d439-4e1c-8356-c6774fe91705
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T16:32:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ea43556-c1c6-4ae7-9c49-48498a82f797 # CK Editor - Extended
            handle: text
            instructions: null
            label: Text
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e613ce4-af24-4647-b186-0eb47bd0c90e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T16:18:20+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f936530d-29a5-4460-9ccd-b586bfb25329 # Call to actions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04fe7c6a-e4d1-47c2-96b7-47f8f0d0a069
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ffbe3148-371c-4de0-b45f-68c3184dc9ae
        userCondition: null
    thumbFieldKey: null
handle: textColumnBlock
hasTitleField: false
icon: null
name: 'Text column block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{blockTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
