allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  f4023492-353e-4a86-9695-455793644dc4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc671e99-b18e-4bf8-87ad-2be57587de6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:44:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ea43556-c1c6-4ae7-9c49-48498a82f797 # CK Editor - Extended
            handle: text
            instructions: null
            label: Text
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97d182aa-ac77-4c14-82e3-07efbc244e18
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T10:12:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f936530d-29a5-4460-9ccd-b586bfb25329 # Call to actions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 123f1b2e-8968-4e21-92e2-f770e960a817
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f15e1db3-4e58-4ab3-81b3-b6f1b2d5bb74
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
                  layoutElementUid: f15e1db3-4e58-4ab3-81b3-b6f1b2d5bb74
                  operator: notempty
                  uid: dd0718d5-3a84-4506-af11-190482c8caa2
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 8c9b2c5d-02c2-4105-83ed-93563621e752 # Position Left/Right
            handle: position
            instructions: null
            label: 'Image position'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aea3eb8a-15e5-4db6-bc7d-343295ff324a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-09-28T10:25:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
                  layoutElementUid: f15e1db3-4e58-4ab3-81b3-b6f1b2d5bb74
                  operator: notempty
                  uid: 6fbd0d7e-d6e7-434a-aef9-1c40f4c73475
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: edbc78b6-631e-4f96-a990-9b8721366f4c # Text + Image Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb97b03e-99cd-4eb6-8b4e-f30156f369fd
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-17T12:37:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 872eeeca-445c-4f8f-a3f9-6ef0c2e3af98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3cac461-fd7a-4f9a-8486-520f99041b3f
        userCondition: null
    thumbFieldKey: null
handle: textImage
hasTitleField: false
icon: text
name: 'Text (+ Image)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
