columnSuffix: null
handle: backgroundColor
instructions: null
name: 'Background Color'
searchable: false
settings:
  dataSet: 'Background colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
