columnSuffix: null
handle: blockTitle
instructions: null
name: 'Title (Anchor)'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
