columnSuffix: null
handle: gtmHead
instructions: "Copy paste the GTM Head code snippet here.\r\n"
name: GTM-Head
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
