columnSuffix: null
handle: socialLinks
instructions: null
name: 'Social Links'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 46d62250-0595-48c1-8a6a-5dac519d54f9
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - 96bee86f-7a09-41f5-bd83-1277ee863484
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - facebook
                            2:
                              - label
                              - Facebook
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-04T09:20:19+00:00'
                            11:
                              - uid
                              - ff629c9f-fdcf-49af-a2ff-e109c82c3bcb
                            14:
                              - fieldUid
                              - f694fce1-48ca-4bfe-9fba-196195547a36 # URL field
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - twitter
                            2:
                              - label
                              - 'X (twitter)'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-04T09:20:19+00:00'
                            11:
                              - uid
                              - 47c22e86-9f0f-4ad6-9946-38b0d0fc8548
                            14:
                              - fieldUid
                              - f694fce1-48ca-4bfe-9fba-196195547a36 # URL field
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - bluesky
                            2:
                              - label
                              - Bluesky
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-04T09:20:19+00:00'
                            11:
                              - uid
                              - bc7a3e7a-4cc5-4e86-8f56-20b6f87c42aa
                            14:
                              - fieldUid
                              - f694fce1-48ca-4bfe-9fba-196195547a36 # URL field
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - linkedin
                            2:
                              - label
                              - Linkedin
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-04T09:20:19+00:00'
                            11:
                              - uid
                              - c8b57ceb-2dc9-45f1-bb4c-9054178a637e
                            14:
                              - fieldUid
                              - f694fce1-48ca-4bfe-9fba-196195547a36 # URL field
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - instagram
                            2:
                              - label
                              - Instagram
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-04T09:20:19+00:00'
                            11:
                              - uid
                              - 447dacdc-12cc-42c1-a21e-aeea9ff21640
                            14:
                              - fieldUid
                              - f694fce1-48ca-4bfe-9fba-196195547a36 # URL field
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - youtube
                            2:
                              - label
                              - Youtube
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-04T09:20:19+00:00'
                            11:
                              - uid
                              - 7e42b7e5-49a5-4b47-89b2-5c639ecfa72d
                            14:
                              - fieldUid
                              - f694fce1-48ca-4bfe-9fba-196195547a36 # URL field
            3:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
