altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  646269a2-695f-4c28-84d9-cb303c2c6167:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-22T09:06:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ba2683a8-065d-492e-9440-02c8cd17adeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T09:09:02+00:00'
            elementCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca164717-6855-492b-9d1f-5f58cf4cd4fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T09:09:02+00:00'
            elementCondition: null
            fieldUid: bcf87482-b5f3-4be6-9a63-153f0458466b # Image Copyright
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1770c7b8-eaed-42f3-95fc-5ce22a6bd28c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T09:09:02+00:00'
            elementCondition: null
            fieldUid: 5a25f3e9-a180-4a29-aa41-8721fbf815b9 # Optimized Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fd87895-765b-4a82-808e-5cb58f301826
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T09:09:02+00:00'
            elementCondition: null
            fieldUid: 60b48ff5-1ab2-471b-8592-cdc623e0882c # Optimized Text Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7fb2c81-3863-4e48-8c36-404df76bd83b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T09:09:02+00:00'
            elementCondition: null
            fieldUid: 0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d # Optimized Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4a74322-97bf-4700-a7b1-78249f819e6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T09:09:02+00:00'
            elementCondition: null
            fieldUid: 197566c6-94bb-4e67-86d7-8945f2589a1d # Optimized Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cefc090-6c53-4241-b1ff-e5ad3fea328e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7647c42f-7780-4d98-bb7a-695131bdc4b6
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
