altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  61da3cfb-4abd-4129-be89-6d00359d5d16:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T12:28:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 84124ebc-eec6-4c73-b47f-0897a75c6f58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T12:29:37+00:00'
            elementCondition: null
            fieldUid: 5a25f3e9-a180-4a29-aa41-8721fbf815b9 # Optimized Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b05b34bd-796d-41a7-892d-a66e6602fa4d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T12:29:37+00:00'
            elementCondition: null
            fieldUid: 197566c6-94bb-4e67-86d7-8945f2589a1d # Optimized Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86c2b72e-42f5-425b-ba7e-d53d2d0bce8d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T12:29:37+00:00'
            elementCondition: null
            fieldUid: 0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d # Optimized Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4adfd1ff-b563-4730-ad87-96d5ea4f749e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T12:29:37+00:00'
            elementCondition: null
            fieldUid: 60b48ff5-1ab2-471b-8592-cdc623e0882c # Optimized Text Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 354c6bd3-4233-4292-ad38-dc805eef7e4d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7026bc73-ff33-4d8e-a537-13e12ef68aaf
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
