columnSuffix: null
handle: ckEditorTable
instructions: null
name: 'CK Editor - Table'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels:
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: null
  options:
    code:
      indentSequence: '  '
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - sourceEditing
    - bold
    - italic
    - insertTable
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
