columnSuffix: null
handle: ckEditorExtended
instructions: null
name: 'CK Editor - Extended'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 25f93ead-d3f6-4049-ba98-6378754f4289 # Extended
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
