columnSuffix: null
handle: ckEditorExtendedWithoutH3
instructions: null
name: 'CK Editor - Extended without H3'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: ea302929-bdb1-4267-a95e-4412305a068e # Extended without H3
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
