columnSuffix: null
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d86336d6-7efa-44f9-9a10-8619c79beeca # Text (+ Image)
    -
      __assoc__:
        -
          - uid
          - 1e4267e1-8d5f-4312-8458-86b19bc17d74 # Text (2 columns)
    -
      __assoc__:
        -
          - uid
          - 7b5ab248-6255-4b42-88bc-80c1dee62b20 # Call To Action
    -
      __assoc__:
        -
          - uid
          - 24bd0074-b53d-404d-9285-a0be9f26bbd4 # Overview
    -
      __assoc__:
        -
          - uid
          - 0396f80c-a192-4beb-a6e7-075075cf0f70 # Image
    -
      __assoc__:
        -
          - uid
          - 7256a782-20ff-4771-9d85-ed3f49e13ef4 # Quote
    -
      __assoc__:
        -
          - uid
          - 209777db-293c-48b6-9897-1fe97b278510 # Video
    -
      __assoc__:
        -
          - uid
          - 95920915-f806-4fbc-9c22-979ec9085fe8 # Text + Video
    -
      __assoc__:
        -
          - uid
          - f2d33237-c7de-4590-9683-7efe6594ebbd # Custom Table
    -
      __assoc__:
        -
          - uid
          - f3211a4e-d5f8-4514-a372-c5b8cfc2c44a # Form
    -
      __assoc__:
        -
          - uid
          - 74b929e4-c99f-4da0-80c7-16d8434d09f6 # FAQ
    -
      __assoc__:
        -
          - uid
          - 4cfdbd85-009b-4c7f-a53c-1a4650483498 # Embed
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
