columnSuffix: null
handle: form
instructions: 'Select a form in the list below to appear in this block.'
name: 'Content Builder - Form - Form'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: verbb\formie\fields\Forms
