columnSuffix: null
handle: gridLayout
instructions: null
name: 'Grid layout'
searchable: false
settings:
  customOptions: false
  iconsOnly: true
  options:
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - full
        -
          - icon
          - '@modules/statik/icons/grid/full.svg'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '1/2 + 1/2'
        -
          - value
          - halves
        -
          - icon
          - '@modules/statik/icons/grid/halves.svg'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1/3 + 1/3 + 1/3'
        -
          - value
          - thirds
        -
          - icon
          - '@modules/statik/icons/grid/thirds.svg'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1/3 + 2/3'
        -
          - value
          - thirdTwoThirds
        -
          - icon
          - '@modules/statik/icons/grid/thirdTwoThirds.svg'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2/3 + 1/3'
        -
          - value
          - twoThirdsThird
        -
          - icon
          - '@modules/statik/icons/grid/twoThirdsThird.svg'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
