columnSuffix: null
handle: gridAlignment
instructions: null
name: 'Grid vertical alignment'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - start
        -
          - icon
          - arrow-up-to-line
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - icon
          - arrows-to-line
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - end
        -
          - icon
          - arrow-down-to-line
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
