columnSuffix: null
handle: gtmBody
instructions: 'Copy paste the GTM Body code snippet here.'
name: GTM-Body
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
