columnSuffix: null
handle: images
instructions: 'The minimum width for this image is 1200px. The ideal width is 2400px'
name: Images
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:cb2bc62e-af93-4687-a676-f92646f90c2d' # Public Files
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:cb2bc62e-af93-4687-a676-f92646f90c2d' # Public Files
  restrictedLocationSubpath: null
  selectionLabel: 'Add an image'
  showCardsInGrid: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
