columnSuffix: null
contentColumnType: text
handle: imageCaption
instructions: 'This will most likely be visible below the image'
name: 'Image Caption'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
