columnSuffix: null
contentColumnType: text
handle: intro
instructions: 'Write a short and snappy text as an introduction to the content on the page. This will probably be displayed below the page title.'
name: 'Intro Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 131a4f6d-f00f-4238-b846-dd504bf669fe # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: statik.json
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
