columnSuffix: null
handle: lightswitchDefaultOn
instructions: null
name: 'Lightswitch (Default On)'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
