columnSuffix: null
handle: lightswitchDefaultOff
instructions: null
name: 'Lightswitch (Default Off)'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
