columnSuffix: null
handle: mobileOrder
instructions: 'Position of this column when the columns are stacked on small screens. Auto keeps the order from left to right.'
name: 'Mobile order'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - ''
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - '1'
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
