columnSuffix: null
handle: mobileTable
instructions: null
name: 'Mobile Table'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Cards
        -
          - value
          - cards
        -
          - icon
          - rectangle
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Scroll
        -
          - value
          - scroll
        -
          - icon
          - computer-mouse-scrollwheel
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
