columnSuffix: null
contentColumnType: string
handle: newsCategory
instructions: ''
name: 'News Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  maintainHierarchy: true
  selectionLabel: ''
  showSiteMenu: true
  sources:
    - 'section:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
