columnSuffix: null
handle: overviewTitle
instructions: 'This title will be displayed on the overview card for this page when shown on another page. As a default the page title is shown as a backup if you don''t fill this field.'
name: 'Overview title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
