columnSuffix: null
contentColumnType: text
handle: overviewDescription
instructions: null
name: 'Overview description'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 131a4f6d-f00f-4238-b846-dd504bf669fe # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: statik.json
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
