columnSuffix: null
handle: overviewDescription
instructions: 'Write a short and snappy text as a summary to the content on the page. This will be displayed on the overview card for this page when shown on another page. As a default the intro text is shown as a backup if you don''t fill this field.'
name: 'Overview description'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 131a4f6d-f00f-4238-b846-dd504bf669fe # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: statik.json
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
