columnSuffix: null
handle: overviewDescription
instructions: null
name: 'Overview description'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels:
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: Simple.json
  options: null
  purifierConfig: statik.json
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - bold
    - italic
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
