columnSuffix: null
handle: positionLeftRightFull
instructions: null
name: 'position (left,right,full)'
searchable: false
settings:
  default: right
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - ''
      -
        - right
        - '1'
      -
        - full
        - '1'
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: none
type: rias\positionfieldtype\fields\Position
