columnSuffix: null
handle: positionLeftRight
instructions: null
name: 'Position Left/Right'
searchable: false
settings:
  default: left
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - ''
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: language
type: rias\positionfieldtype\fields\Position
