columnSuffix: null
handle: quote
instructions: null
name: Quote
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
