columnSuffix: null
contentColumnType: text
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  allowSitenameDisable: ''
  allowSitenameOverwrite: ''
  tabs:
    __assoc__:
      -
        - general
        - '1'
      -
        - facebook
        - '1'
      -
        - twitter
        - '1'
translationKeyFormat: null
translationMethod: site
type: studioespresso\seofields\fields\SeoField
