columnSuffix: null
handle: textColumnBlocks
instructions: null
name: 'Text column blocks'
searchable: false
settings:
  createButtonLabel: 'New Column'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - e94342b2-ffae-4392-93ba-42e9e60ae378 # Text column block
        -
          - group
          - General
  includeTableView: false
  maxEntries: 3
  minEntries: 2
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
