columnSuffix: null
handle: titleText
instructions: null
name: 'Title + Text'
searchable: false
settings:
  createButtonLabel: 'Add a Title Text block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - e2f5eec1-592f-413d-ad26-6b2637e3ec8a # Title + Text
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
