columnSuffix: null
handle: video
instructions: 'Paste the URL of a YouTube or Vimeo video. '
name: 'Content Builder - Video - Video'
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
