columnSuffix: null
contentColumnType: string(255)
handle: youtube
instructions: ''
name: Youtube
searchable: true
settings:
  maxLength: 255
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
