columnSuffix: null
handle: youtube
instructions: null
name: Youtube
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
