dateModified: 1758629750
email:
  fromEmail: support@statik.be
  fromName: craft
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3dd47c7b-c4f7-4194-b53a-82300558694c: craft # craft
    6be28258-6088-4b4c-9a1c-42295f9229fd: craft # craft
    53dc3fb5-ea5b-4073-bfef-6466b15074db: ffdsfa # ffdsfa
    bb9997b7-3c93-4329-819f-c7edbdfb46f8: ffdsa # ffdsa
plugins:
  carbon-tracker:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  config-values-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookie-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  craft-sentry:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-index-defaults:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: craft
  schemaVersion: 6.0.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
