<?php

namespace modules\statik\variables;

use craft\base\ElementInterface;
use craft\elements\Entry;
use modules\statik\helpers\ContentbuilderShowcase;
use modules\statik\helpers\GridBuilder;

/**
 * @author    Statik
 * @package   Statik
 * @since     1.0.0
 */
class StatikVariable
{
    /**
     * Describes the variation a Content Builder block is in, for the pages generated by `craft statik/contentbuilder`.
     */
    public function contentbuilderShowcaseLabel(ElementInterface $block): string
    {
        return ContentbuilderShowcase::describe($block);
    }

    /**
     * Layout and columns (cell, effective width, image sizes) of a "Grid row" content builder block.
     */
    public function gridRow(Entry $row): array
    {
        return GridBuilder::row($row);
    }
}
