<?php

namespace modules\statik\variables;

use craft\base\ElementInterface;
use craft\elements\Entry;
use modules\statik\helpers\ContentbuilderShowcase;
use modules\statik\helpers\GridBuilder;

/**
 * @author    Statik
 * @package   Statik
 * @since     1.0.0
 */
class StatikVariable
{
    /**
     * Describes the variation a Content Builder block is in, for the pages generated by `craft statik/contentbuilder`.
     */
    public function contentbuilderShowcaseLabel(ElementInterface $block): string
    {
        return ContentbuilderShowcase::describe($block);
    }

    /**
     * Whether this page belongs to the content builder or grid row showcase, generated by `craft statik/contentbuilder`.
     */
    public function isContentbuilderShowcasePage(ElementInterface $page): bool
    {
        return ContentbuilderShowcase::isShowcasePage($page);
    }

    /**
     * Whether this is the showcase page that renders the content builder at 2/3 width.
     */
    public function isShowcaseNarrowPage(ElementInterface $page): bool
    {
        return ContentbuilderShowcase::isNarrowPage($page);
    }

    /**
     * Layout and columns (cell, effective width, image sizes) of a "Grid row" content builder block.
     */
    public function gridRow(Entry $row): array
    {
        return GridBuilder::row($row);
    }
}
