<?php

namespace modules\statik\variables;

use craft\base\ElementInterface;
use modules\statik\helpers\ContentbuilderShowcase;

/**
 * @author    Statik
 * @package   Statik
 * @since     1.0.0
 */
class StatikVariable
{
    /**
     * Describes the variation a Content Builder block is in, for the pages generated by `craft statik/contentbuilder`.
     */
    public function contentbuilderShowcaseLabel(ElementInterface $block): string
    {
        return ContentbuilderShowcase::describe($block);
    }
}
