<?php

namespace modules\statik\console\controllers;

use Craft;
use craft\console\Controller;
use craft\elements\Entry;
use craft\helpers\Console;
use craft\helpers\Json;
use modules\statik\helpers\ContentbuilderShowcase;
use yii\console\ExitCode;

/**
 * Removes the Content Builder showcase generated by `craft statik/contentbuilder`: the "contentbuilder"
 * page with all its child pages, and optionally the imported showcase images.
 *
 * Usage:
 *   ddev craft statik/contentbuilder-cleanup                   Remove the showcase pages (moved to the trash)
 *   ddev craft statik/contentbuilder-cleanup --with-images     …and delete the showcase image folder
 *   ddev craft statik/contentbuilder-cleanup --hard-delete     Delete permanently instead of moving to the trash
 *   ddev craft statik/contentbuilder-cleanup --interactive=0   Don't ask for confirmation
 *
 * To also remove the showcase code from the templates, use the `removing-contentbuilder-showcase` Claude skill.
 */
class ContentbuilderCleanupController extends Controller
{
    public $defaultAction = 'index';

    /** @var bool Also delete the folder with the imported showcase images */
    public bool $withImages = false;

    /** @var bool Delete permanently instead of moving to the trash */
    public bool $hardDelete = false;

    public function options($actionID): array
    {
        return array_merge(parent::options($actionID), ['withImages', 'hardDelete']);
    }

    public function actionIndex(): int
    {
        $parent = ContentbuilderShowcase::findParentPage();
        if ($parent) {
            $children = $parent->getDescendants()->status(null)->all();
            $question = "Delete \"{$parent->title}\" and its " . count($children) . ' child pages' . ($this->hardDelete ? ' permanently' : '') . '?';
            if ($this->confirm($question, true)) {
                $this->deletePages($parent, $children);
            }
        } else {
            $this->stdout('No showcase page found (slug "' . ContentbuilderShowcase::parentSlug() . '" in "' . ContentbuilderShowcase::SECTION_HANDLE . '").' . PHP_EOL, Console::FG_YELLOW);
        }

        if ($this->withImages) {
            $this->deleteImages();
        }

        return ExitCode::OK;
    }

    /**
     * @param Entry[] $children
     */
    private function deletePages(Entry $parent, array $children): void
    {
        $elements = Craft::$app->getElements();
        // Deepest pages first, so the structure stays valid while deleting
        foreach (array_reverse($children) as $child) {
            $elements->deleteElement($child, $this->hardDelete);
            $this->stdout("✓ Deleted \"{$child->title}\"" . PHP_EOL, Console::FG_GREEN);
        }
        $elements->deleteElement($parent, $this->hardDelete);
        $this->stdout("✓ Deleted \"{$parent->title}\"" . PHP_EOL, Console::FG_GREEN);
    }

    private function deleteImages(): void
    {
        $settings = is_file(ContentbuilderShowcase::CONTENT_PATH)
            ? (Json::decode(file_get_contents(ContentbuilderShowcase::CONTENT_PATH))['assets'] ?? [])
            : [];
        $volumeHandle = $settings['volume'] ?? 'publicFiles';
        $path = trim($settings['folder'] ?? 'contentbuilder-showcase', '/') . '/';

        $volume = Craft::$app->getVolumes()->getVolumeByHandle($volumeHandle);
        $folder = $volume ? Craft::$app->getAssets()->findFolder(['volumeId' => $volume->id, 'path' => $path]) : null;
        if (!$folder) {
            $this->stdout("No showcase image folder found ({$volumeHandle}: {$path})." . PHP_EOL, Console::FG_YELLOW);
            return;
        }

        if ($this->confirm("Delete the image folder \"{$path}\" and all files in it?", true)) {
            Craft::$app->getAssets()->deleteFoldersByIds($folder->id);
            $this->stdout("✓ Deleted image folder \"{$path}\"" . PHP_EOL, Console::FG_GREEN);
        }
    }
}
