defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9f39fdda-793c-4506-9dd4-e764d46cad28 # Contentbuilder Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: '{parent.uri}/{slug}'
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: '{parent.uri}/{slug}'
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 8839fbe4-d531-4ccd-9d5d-2ec8517196f6
type: structure
