description: ''
handle: contentManagers
name: 'Content Managers'
permissions:
  - accesscp
  - accessplugin-formie
  - accessplugin-navigate
  - accessplugin-seo-fields
  - accessplugin-translate
  - administrateusers
  - 'assignusergroup:3196b984-5af4-44dd-a6db-ac2c8f7924d9' # Content Managers
  - 'createentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'createentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'createentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'createfolders:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'deleteassets:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'deleteentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'deleteentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'deleteentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'deletepeerassets:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'deletepeerentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'deletepeerentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'deletepeerentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'deletepeerentrydrafts:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'deletepeerentrydrafts:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'deletepeerentrydrafts:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'deletepeerentrydrafts:4750849d-9328-4d3e-956d-9d317da5e6eb' # Page not found
  - 'deletepeerentrydrafts:4c32edae-2824-4f0f-b38b-2477d2500dfe' # News Overview
  - 'deletepeerentrydrafts:5611e98d-93ec-4bd4-95dd-18f282b8c5e8' # Home
  - 'deletepeerentrydrafts:5d236e94-b6a8-472c-9296-a5c992cdd49a' # Contact
  - 'deletepeerentrydrafts:6f79e12f-9d80-4f17-ae51-5160127975ec' # Site Settings
  - 'deletepeerentrydrafts:99a435d2-9c12-4ef6-8b3b-2a9915d4216b' # Accessibility Statement
  - 'deletepeerentrydrafts:c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e' # Privacy policy
  - 'deletepeerentrydrafts:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'deletepeerentrydrafts:e3bed4e1-82ae-45e8-908c-0a6669141b31' # Search results
  - 'editimages:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'editpeerimages:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'editsite:6de046f0-6167-4af1-aa91-ffaf83e36a14' # NL
  - 'editsite:e57cf13b-f9cb-484a-8093-a897fa43eb68' # EN
  - 'editsite:fd2014b7-5bc0-49a9-ac30-e009081532f7' # FR
  - editusers
  - formie-accessforms
  - formie-accesssentnotifications
  - formie-accesssubmissions
  - formie-createforms
  - formie-deleteforms
  - formie-manageforms
  - 'formie-manageforms:467c13f5-4b29-4a9c-8350-4a2176984b2e'
  - 'formie-manageforms:f79ffac4-09f3-44fa-a6c7-efef86bb1c30'
  - formie-viewsentnotifications
  - 'formie-viewsentnotifications:467c13f5-4b29-4a9c-8350-4a2176984b2e'
  - 'formie-viewsentnotifications:f79ffac4-09f3-44fa-a6c7-efef86bb1c30'
  - formie-viewsubmissions
  - 'formie-viewsubmissions:467c13f5-4b29-4a9c-8350-4a2176984b2e'
  - 'formie-viewsubmissions:f79ffac4-09f3-44fa-a6c7-efef86bb1c30'
  - moderateusers
  - registerusers
  - 'replacefiles:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'replacepeerfiles:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'saveassets:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'saveentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'saveentries:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'saveentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'saveentries:4750849d-9328-4d3e-956d-9d317da5e6eb' # Page not found
  - 'saveentries:4c32edae-2824-4f0f-b38b-2477d2500dfe' # News Overview
  - 'saveentries:5611e98d-93ec-4bd4-95dd-18f282b8c5e8' # Home
  - 'saveentries:5d236e94-b6a8-472c-9296-a5c992cdd49a' # Contact
  - 'saveentries:6f79e12f-9d80-4f17-ae51-5160127975ec' # Site Settings
  - 'saveentries:99a435d2-9c12-4ef6-8b3b-2a9915d4216b' # Accessibility Statement
  - 'saveentries:c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e' # Privacy policy
  - 'saveentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'saveentries:e3bed4e1-82ae-45e8-908c-0a6669141b31' # Search results
  - 'savepeerassets:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'savepeerentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'savepeerentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'savepeerentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'savepeerentrydrafts:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'savepeerentrydrafts:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'savepeerentrydrafts:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'savepeerentrydrafts:4750849d-9328-4d3e-956d-9d317da5e6eb' # Page not found
  - 'savepeerentrydrafts:4c32edae-2824-4f0f-b38b-2477d2500dfe' # News Overview
  - 'savepeerentrydrafts:5611e98d-93ec-4bd4-95dd-18f282b8c5e8' # Home
  - 'savepeerentrydrafts:5d236e94-b6a8-472c-9296-a5c992cdd49a' # Contact
  - 'savepeerentrydrafts:6f79e12f-9d80-4f17-ae51-5160127975ec' # Site Settings
  - 'savepeerentrydrafts:99a435d2-9c12-4ef6-8b3b-2a9915d4216b' # Accessibility Statement
  - 'savepeerentrydrafts:c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e' # Privacy policy
  - 'savepeerentrydrafts:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'savepeerentrydrafts:e3bed4e1-82ae-45e8-908c-0a6669141b31' # Search results
  - 'seo-fields:notfound'
  - 'seo-fields:redirects'
  - 'viewassets:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'viewentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'viewentries:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'viewentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'viewentries:4750849d-9328-4d3e-956d-9d317da5e6eb' # Page not found
  - 'viewentries:4c32edae-2824-4f0f-b38b-2477d2500dfe' # News Overview
  - 'viewentries:5611e98d-93ec-4bd4-95dd-18f282b8c5e8' # Home
  - 'viewentries:5d236e94-b6a8-472c-9296-a5c992cdd49a' # Contact
  - 'viewentries:6f79e12f-9d80-4f17-ae51-5160127975ec' # Site Settings
  - 'viewentries:99a435d2-9c12-4ef6-8b3b-2a9915d4216b' # Accessibility Statement
  - 'viewentries:c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e' # Privacy policy
  - 'viewentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'viewentries:e3bed4e1-82ae-45e8-908c-0a6669141b31' # Search results
  - 'viewpeerassets:cb2bc62e-af93-4687-a676-f92646f90c2d' # Files
  - 'viewpeerentries:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'viewpeerentries:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'viewpeerentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'viewpeerentrydrafts:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
  - 'viewpeerentrydrafts:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'viewpeerentrydrafts:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
  - 'viewpeerentrydrafts:4750849d-9328-4d3e-956d-9d317da5e6eb' # Page not found
  - 'viewpeerentrydrafts:4c32edae-2824-4f0f-b38b-2477d2500dfe' # News Overview
  - 'viewpeerentrydrafts:5611e98d-93ec-4bd4-95dd-18f282b8c5e8' # Home
  - 'viewpeerentrydrafts:5d236e94-b6a8-472c-9296-a5c992cdd49a' # Contact
  - 'viewpeerentrydrafts:6f79e12f-9d80-4f17-ae51-5160127975ec' # Site Settings
  - 'viewpeerentrydrafts:99a435d2-9c12-4ef6-8b3b-2a9915d4216b' # Accessibility Statement
  - 'viewpeerentrydrafts:c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e' # Privacy policy
  - 'viewpeerentrydrafts:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News items
  - 'viewpeerentrydrafts:e3bed4e1-82ae-45e8-908c-0a6669141b31' # Search results
