defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6122281a-7d92-44b0-bef8-296775631068 # Simple page (Title/Intro/SEO)
handle: confirmAccount
maxAuthors: 1
name: 'Confirm your account'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_registrationConfirmation.twig
    uriFormat: bevestig-je-account
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_registrationConfirmation.twig
    uriFormat: confirm-your-account
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_registrationConfirmation.twig
    uriFormat: confirmez-votre-compte
type: single
