defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bb9997b7-3c93-4329-819f-c7edbdfb46f8 # ffdsa
handle: ffdsfa
maxAuthors: 1
name: ffdsfa
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3dd47c7b-c4f7-4194-b53a-82300558694c: # craft
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
