tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-03-26T17:48:02+01:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: e2c1374a-042a-48b6-992c-843e0bc06a1d
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-03-26T17:48:02+01:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: fbe0c3e5-68a4-41b5-9d68-bda77dc600d1
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-03-26T17:48:02+01:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 9c557736-0321-4cce-8151-d7c172e88818
        userCondition: null
        warning: null
    name: Content
    uid: d44b6ca6-80b4-4917-be20-69ba8da466f7
    userCondition: null
